# Generated by Django 2.2.8 on 2023-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=50)),
                ('result', models.CharField(default='System Error', max_length=500)),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('testcase', models.CharField(default='unknow', max_length=500)),
                ('casedata', models.CharField(max_length=500)),
                ('outputdata', models.CharField(default='', max_length=500)),
                ('useroutput', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('oj', models.CharField(default='LPOJ', max_length=50)),
                ('problem', models.CharField(max_length=50)),
                ('result', models.IntegerField()),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('length', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('submittime', models.DateTimeField()),
                ('judger', models.CharField(max_length=50)),
                ('contest', models.IntegerField()),
                ('contestproblem', models.IntegerField(default=-1)),
                ('code', models.TextField(max_length=200000)),
                ('testcase', models.CharField(default='0', max_length=50)),
                ('message', models.TextField()),
                ('problemtitle', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=1500)),
                ('ip', models.CharField(default='无法获取ip', max_length=50)),
            ],
        ),
    ]
