# Generated by Django 2.2.8 on 2023-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regtime', models.DateTimeField(auto_now=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=50)),
                ('classes', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('qq', models.CharField(default='', max_length=50, null=True)),
                ('email', models.CharField(default='', max_length=50, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ac', models.IntegerField(default=0)),
                ('submit', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=50, null=True)),
                ('rating', models.IntegerField(default=1500)),
                ('acpro', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ip', models.CharField(default='unknow', max_length=50, null=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
    ]
