# Generated by Django 2.2.8 on 2023-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBCode',
            fields=[
                ('username', models.CharField(default='std', max_length=50, primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBCodeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='std', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(default='none', max_length=1000)),
                ('group', models.CharField(default='none', max_length=50)),
                ('code', models.TextField(default='暂无代码')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainningContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=500)),
                ('tips', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('group', models.IntegerField()),
                ('num', models.IntegerField()),
                ('problem', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='std', max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('value', models.TextField(default='暂无文本')),
                ('time', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(default='', max_length=50, null=True)),
                ('std', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
