# Generated by Django 2.2.8 on 2023-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChoiceProblemId', models.IntegerField(default=-1)),
                ('des', models.TextField()),
                ('choiceA', models.TextField()),
                ('choiceB', models.TextField()),
                ('choiceC', models.TextField()),
                ('choiceD', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(default='admin', max_length=50)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('oj', models.CharField(default='LPOJ', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('des', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sinput', models.TextField()),
                ('soutput', models.TextField()),
                ('source', models.TextField()),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('hint', models.TextField(default='', null=True)),
                ('auth', models.IntegerField(default=1)),
                ('template', models.CharField(default='请删除这行', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('problem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('level', models.IntegerField(default=5)),
                ('submission', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('mle', models.IntegerField(default=0)),
                ('tle', models.IntegerField(default=0)),
                ('rte', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('ce', models.IntegerField(default=0)),
                ('wa', models.IntegerField(default=0)),
                ('se', models.IntegerField(default=0)),
                ('tag', models.TextField(null=True)),
                ('score', models.IntegerField(default=1000)),
                ('auth', models.IntegerField(default=1)),
                ('oj', models.CharField(default='LPOJ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
